### ISSUE TITLE
Special character in dataframe column name

### ISSUE THREAD

**Issue by GregFa** [senresearch/GeneNetworkAPI.jl#5]
The function `run_correlation()` returns a data frame where the first column is `#_strains`. This column name should be renamed.

**Comment by sens** [comment]
That is probably okay.  The function is returning a list of traits that are correlated to some degree in a dataset. the `#_strains` gives the number of strains in which that trait was measured (we were looking at the BXD strains).  So, I think it is a legit column name, although I agree with you that the naming is unfortunate.  Perhaps this is an issue with the GN backend?
